apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: 
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_DB: "mydb"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"