apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: PROJECT/IMAGE_BACKUP
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "300m"
                  memory: "256Mi"
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_DB
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_HOST
                - name: POSTGRES_PORT
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PORT
                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: gcp-backup
                      key: BUCKET_NAME
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/SERVICE_ACCOUNT_JSON
              command: ["/bin/bash", "-c"]
              args:
                - export URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}" &&
                  ./backup.sh
              volumeMounts:
                - name: gcp-creds
                  mountPath: /secrets
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: gcp-creds
              secret:
                secretName: gcp-backup
                items:
                - key: SERVICE_ACCOUNT_JSON
                  path: SERVICE_ACCOUNT_JSON
